/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UserProgressRouteImport } from './routes/user-progress'
import { Route as StudyGuidesRouteImport } from './routes/study-guides'
import { Route as PdfUploadRouteImport } from './routes/pdf-upload'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as EmbeddingsRouteImport } from './routes/embeddings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProgressRoute = UserProgressRouteImport.update({
  id: '/user-progress',
  path: '/user-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyGuidesRoute = StudyGuidesRouteImport.update({
  id: '/study-guides',
  path: '/study-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfUploadRoute = PdfUploadRouteImport.update({
  id: '/pdf-upload',
  path: '/pdf-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingsRoute = EmbeddingsRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/embeddings': typeof EmbeddingsRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/pdf-upload': typeof PdfUploadRoute
  '/study-guides': typeof StudyGuidesRoute
  '/user-progress': typeof UserProgressRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/embeddings': typeof EmbeddingsRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/pdf-upload': typeof PdfUploadRoute
  '/study-guides': typeof StudyGuidesRoute
  '/user-progress': typeof UserProgressRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRoute
  '/embeddings': typeof EmbeddingsRoute
  '/exercises': typeof ExercisesRoute
  '/login': typeof LoginRoute
  '/pdf-upload': typeof PdfUploadRoute
  '/study-guides': typeof StudyGuidesRoute
  '/user-progress': typeof UserProgressRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/calculator'
    | '/dashboard'
    | '/embeddings'
    | '/exercises'
    | '/login'
    | '/pdf-upload'
    | '/study-guides'
    | '/user-progress'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/calculator'
    | '/dashboard'
    | '/embeddings'
    | '/exercises'
    | '/login'
    | '/pdf-upload'
    | '/study-guides'
    | '/user-progress'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/calculator'
    | '/dashboard'
    | '/embeddings'
    | '/exercises'
    | '/login'
    | '/pdf-upload'
    | '/study-guides'
    | '/user-progress'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRoute
  EmbeddingsRoute: typeof EmbeddingsRoute
  ExercisesRoute: typeof ExercisesRoute
  LoginRoute: typeof LoginRoute
  PdfUploadRoute: typeof PdfUploadRoute
  StudyGuidesRoute: typeof StudyGuidesRoute
  UserProgressRoute: typeof UserProgressRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-progress': {
      id: '/user-progress'
      path: '/user-progress'
      fullPath: '/user-progress'
      preLoaderRoute: typeof UserProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-guides': {
      id: '/study-guides'
      path: '/study-guides'
      fullPath: '/study-guides'
      preLoaderRoute: typeof StudyGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-upload': {
      id: '/pdf-upload'
      path: '/pdf-upload'
      fullPath: '/pdf-upload'
      preLoaderRoute: typeof PdfUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeddings': {
      id: '/embeddings'
      path: '/embeddings'
      fullPath: '/embeddings'
      preLoaderRoute: typeof EmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRoute,
  EmbeddingsRoute: EmbeddingsRoute,
  ExercisesRoute: ExercisesRoute,
  LoginRoute: LoginRoute,
  PdfUploadRoute: PdfUploadRoute,
  StudyGuidesRoute: StudyGuidesRoute,
  UserProgressRoute: UserProgressRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
